# ref: https://tellme.tokyo/post/2020/02/04/release-go-cli-tool/
name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Create Release with Generated Notes
        run: |
          gh release create ${{ github.ref_name }} \
            --generate-notes \
            --title "Release ${{ github.ref_name }}" \
            --verify-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Upload Assets with GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  dockerpublish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: login
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push
        run: |
          TAG=docker.pkg.github.com/${GITHUB_REPOSITORY}/consul-envoy-xds-server:${GITHUB_REF##*/}
          docker build -t $TAG .
          docker push $TAG
